[package]
name = "number_theory"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "enumerate_quotients"
path = "src/enumerate_quotients.rs"

[[bin]]
name = "primality_test"
path = "src/primality_test.rs"

[dependencies]
