[package]
name = "tree"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tree_path_composite_sum"
path = "src/tree_path_composite_sum.rs"

[[bin]]
name = "tree_path_composite_sum2"
path = "src/tree_path_composite_sum2.rs"


[dependencies]
